version: "3"

services:
    db:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "33306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
        container_name: reatla_db
      
    ap:
        build: 
          context: ./python
          args:
            project_directory: "/src/"
        expose:
          - "8080"
        volumes:
          - "./python/src:/projects"
        environment:
            TZ: "Asia/Tokyo"
        container_name: reatla_ap
        depends_on:
            - db
    
    web:
        build: ./nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        environment:
            TZ: "Asia/Tokyo"
        container_name: "reatla_web"
        depends_on:
            - ap

